- id: micube_brightness_rotate_2
  alias: Cube - rotate
  initial_state: 'on'
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/Cube
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.action in [''rotate_right'', ''rotate_left'']
      }}'
  action:
  - service: light.turn_on
    data:
      entity_id: light.strip_bett
  - service: light.turn_on
    data_template:
      entity_id: light.strip_bett
      brightness: '{% if trigger.payload_json.angle | float > 0 %} {{  states.light.strip_bett.attributes.brightness
        | int + (trigger.payload_json.angle | int) }} {% else %} {{  states.light.strip_bett.attributes.brightness
        | int + (trigger.payload_json.angle | int) }} {% endif %}  '
- id: '1546265908242'
  alias: Pushover
  trigger:
  - entity_id: binary_sensor.door_contact
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Door open
    service: notify.notifier_name
